Repository ovh-ux/manager-webpack-dev-server, pull requests merged in 2018-10, with the labels that each got.

#3 fix(github.codeowners): add missing path
  .github/CODEOWNERS
Labels: bug

#6 style(gitattributes): add gitattributes file
  .gitattributes
Labels: enhancement

#5 style(eslint): apply correct indentation
  .eslintrc
Labels: enhancement

#4 fix: remove .npmrc file
  .npmrc
Labels: bug

#2 style(editorconfig): add editorconfig file
  .editorconfig
Labels: enhancement

#7 fix(package.json): rename package
  package.json
Labels: bug

#9 refactor: extract configuration from package.json into json files
  .huskyrc.json
  .lintstagedrc.json
  package.json
Labels: enhancement

#10 fix(config): remove timefixplugin and add https env
  README.md
  config.js
  package.json
  yarn.lock
Labels: bug, enhancement

#11 docs(readme): update readme.md file
  README.md
Labels: enhancement

#13 Generate CHANGELOG.md file
  CHANGELOG.md
  package.json
Labels: enhancement

#12 refactor: move code to src folder
  package.json
  src/config.js
  src/index.js
  src/proxy/aapi/index.js
  src/proxy/dev/index.js
  src/proxy/index.js
  src/sso/index.js
Labels: enhancement
